excluded:
  - Pods
  - Carthage
  - ./**/*.generated.swift
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
#   - file_header
  - file_name
  - first_where
  - force_cast
  - force_try
  - flatmap_over_map_reduce
  - identical_operands
#   - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nesting
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
#   - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
#   - static_operator
#   - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

identifier_name:
  min_length: 1

number_separator:
  minimum_length: 5

line_length:
  warning: 200
  ignores_comments: true
  
function_body_length:
  warning: 200
  error: 300

file_name:
  excluded:
    - main.swift
    - LinuxMain.swift
    - TestHelpers.swift
    - ObservableType+Chaining.swift
    - TagListView+Rx.swift
    - UIResponder+Rx.swift
    - UIScrollView+Rx.swift
    - UIViewController+Rx.swift
    - UserDefaults+Rx.swift
  suffix_pattern: "Extensions?|\\+.*"

nesting:
  type_level:
    warning: 1
  function_level:
    warning: 1

large_tuple:
  warning: 3
  error: 4
