name: Snippets

targets:
  Snippets:
    type: application
    platform: iOS
    sources:
      - Snippets
      - path: Snippets/R.generated.swift
        optional: true
        type: file
      - path: Snippets/Mock.generated.swift
        optional: true
        type: file
    settings:
      base:
        INFOPLIST_FILE: Snippets/Info.plist
        CODE_SIGN_ENTITLEMENTS: Snippets/Snippets.entitlements
        DEVELOPMENT_LANGUAGE: en
        PRODUCT_BUNDLE_IDENTIFIER: com.zyxw.Snippets
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    preBuildScripts:
      - name: Generate Resources with R.swift
        script: |
          xcrun --sdk macosx mint run r.swift generate "$SRCROOT/$PROJECT_NAME/R.generated.swift"
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/$PROJECT_NAME/R.generated.swift
      - name: Generate Mock with Mockolo
        script: |
          rm -f $SRCROOT/$PROJECT_NAME/Mock.generated.swift
          xcrun --sdk macosx mint run mockolo --sourcedirs $SRCROOT/$PROJECT_NAME --destination $SRCROOT/$PROJECT_NAME/Mock.generated.swift --mock-final
        outputFiles:
          - $SRCROOT/$PROJECT_NAME/Mock.generated.swift
      - name: Format Codes
        script: |
          xcrun --sdk macosx mint run swiftformat .
      - name: SwiftLint
        script: |
          xcrun --sdk macosx mint run swiftlint --config "$SRCROOT/.swiftlint.yml"
    dependencies:
      - target: DashSourceful
      - target: Entity
      - target: LanguageThemeColor
      - target: RxPropertyWrapper
      - target: RxPropertyChaining
  DashSourceful:
    templates: 
      - EmbeddedFramework
      - EmbeddedRSwift
  Entity:
    templates: 
      - EmbeddedFramework
  LanguageThemeColor:
    templates:
      - EmbeddedFramework
      - EmbeddedRSwift
  RxPropertyChaining:
    templates: 
      - EmbeddedFramework
  RxPropertyWrapper:
    templates: 
      - EmbeddedFramework

options:
  xcodeVersion: "12.4"
  bundleIdPrefix: com.zyxw
  postGenCommand: pod install

targetTemplates:
  EmbeddedFramework:
    platform: iOS
    type: framework
    sources:
      - path: ${target_name}
    settings:
      INFOPLIST_FILE: ${target_name}/Info.plist
  EmbeddedRSwift:
    sources:
      - path: ${target_name}/${target_name}.R.generated.swift
        optional: true
        type: file
    preBuildScripts:
      - name: Generate Resources with R.swift
        script: |
          xcrun --sdk macosx mint run r.swift generate "$PRODUCT_NAME/$PRODUCT_NAME.R.generated.swift"
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - "$PRODUCT_NAME/$(PRODUCT_NAME).R.generated.swift"
