name: Snippets
targets:
  Snippets:
    type: application
    platform: iOS
    sources:
      - Snippets
      - path: Snippets/R.generated.swift
        optional: true
        type: file
    settings:
      base:
        INFOPLIST_FILE: Snippets/Info.plist
        CODE_SIGN_ENTITLEMENTS: Snippets/Snippets.entitlements
        DEVELOPMENT_LANGUAGE: en
        PRODUCT_BUNDLE_IDENTIFIER: com.zyxw.Snippets
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    preBuildScripts:
      - name: Generate Resources with R.swift
        script: |
          /usr/local/bin/mint run r.swift generate "$SRCROOT/$PROJECT_NAME/R.generated.swift"
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/$PROJECT_NAME/R.generated.swift
      - name: Format Codes
        script: |
          /usr/local/bin/mint run swiftformat .
      - name: SwiftLint
        script: |
          /usr/local/bin/mint run swiftlint --config "$SRCROOT/.swiftlint.yml"
options:
  postGenCommand: pod install
